version: '3.7'

services:
  receiver-proxy:
    image: nginx:alpine
    container_name: receiver-proxy
    ports:
      - '4080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend


networks:
  backend:
    driver: bridge