version: '3.7'

services:
  ws-server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: remi-ws-server
    ports:
      - '3000:3000' #http
      - '3020:3020' #websocket
    volumes:
      - ./ws-server:/app
      - ./ws-server/node_modules:/app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
